#cloud-config

hostname: "nas"

users:
  - name: "nas"
    passwd: "$1$LZOElXOJ$sqPEuqdiZRlYr5Iy.mQLO/"
    groups:
      - "sudo"
      - "docker"

coreos:
  units:
    - name: sshd.service
      command: start
    - name: shellinabox.service
      command: start
      content: |
        [Unit]
        Description=Shell-in-a-box service
        After=docker.service
        Requires=docker.service

        [Service]
        TimeoutStartSec=0
        Environment=SERVICE_NAME=shellinabox
        ExecStartPre=/usr/bin/docker kill $SERVICE_NAME || true
        ExecStartPre=/usr/bin/docker rm $SERVICE_NAME || true
        ExecStartPre=/usr/bin/docker pull fhuegli/shellinabox
        ExecStart=/usr/bin/docker run --name $SERVICE_NAME -p 10022:4200 --add-host="nas:172.17.0.1" -e SIAB_SERVICE="/:SSH:nas" fhuegli/shellinabox
        ExecStop=/usr/bin/docker stop $SERVICE_NAME

        [Install]
        WantedBy=multi-user.target
