#cloud-config

hostname: "nas"

users:
  - name: "nas"
    passwd: "$1$LZOElXOJ$sqPEuqdiZRlYr5Iy.mQLO/"
    groups:
      - "sudo"
      - "docker"

coreos:
  units:
    - name: sshd.service
    command: start
